---
title: "BilboardHot100Ones"
author: "Mateusz Nowaczek, Gabriel Nowak, Jan Pawelec"
date: "2026-05-01"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

# What about

The project is about analyzing a "Billboard Hot 100 Number Ones" dataset
from tidyverse. We have chosen this particular set, because everybody
love music.

Source:
<https://docs.google.com/spreadsheets/d/1j1AUgtMnjpFTz54UdXgCKZ1i4bNxFjf01ImJ-BqBEt0/edit?gid=1974823090#gid=1974823090>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(tidytuesdayR)
library(janitor)
```

# 1. Data Cleaning and Preparation

```{r}
tuesdata <- tidytuesdayR::tt_load('2025-08-26')

billboard_raw <- tuesdata$billboard 
```

Let's have a look on our data.

```{r}
glimpse(billboard_raw)
```

## 1.1. Is na?

```{r}
colSums(is.na(billboard_raw))
```

## 1.2. Complex cleaning

Now we can clean missing values and extra information we have no need to
use.

```{r}
billboard_clean <- billboard_raw %>%
  clean_names() %>%
  select(-contains("lyrics"), -contains("text")) %>%
  mutate(
    across(where(is.character), str_squish)
  ) %>%
  mutate(
    date = lubridate::ymd(date)
  ) %>%
  drop_na(artist, song, date) %>%
  distinct()
  
colSums(is.na(billboard_clean))
```

```{R}
# a few new columns
billboard_test <- billboard_clean

billboard_test <- billboard_test %>% mutate(decade = paste0(floor(year(date) / 10) * 10 , "s"))
billboard_test <- billboard_test %>% mutate(year = paste0(floor(year(date))))
# First two allow for better analysis of the time of release
billboard_test <- billboard_test %>% mutate(is_collab = str_detect(artist, "feat\\.|&|,|and"))
billboard_test <- billboard_test %>% mutate(artist_count = str_count(artist, "&|,|feat\\.") + 1)
# These two make it easier to see if songs performed by multiple people are more popular
billboard_test <- billboard_test %>% mutate(song_title_length = nchar(song))
# This one can be used to see if longer song titles may lead to lower popularity

billboard_test <- billboard_test %>%
  mutate(
  season = case_when(
    month(date) %in% c(12,1,2) ~ "Winter",
    month(date) %in% c(3,4,5) ~ "Spring",
    month(date) %in% c(6,7,8) ~ "Summer",
    TRUE ~ "Autumn"
  )
)
## This allows us to see in what season does the most hit songs get produced
billboard_test %>% count(season)




```
```{R}
# Statistics about length of the song title
max(billboard_test$song_title_length)
min(billboard_test$song_title_length)
mean(billboard_test$song_title_length)

#We can see that there are longer song titles (max == 66) but they tend to be much shorter (mean == 16) [characters long]
```

## Charts

```{R}
#This chart shows us that it doesn't matter when the song was released season wise
ggplot(billboard_test, aes(x = season, fill = season)) +
  geom_bar()

```

```{R}
#This one shows that most popular songs were written in the 70s and 80s
ggplot(billboard_test, aes(x = decade, fill = decade)) +
  geom_bar()
```

```{R}
# number of hits per year
billboard_test %>%
  mutate(year = as.numeric(year)) %>%
  count(year) %>%
  ggplot(aes(x = year, y = n)) +

  geom_line(
    color = "#4E79A7",
    linewidth = 1.2
  ) +

  geom_point(
    color = "#4E79A7",
    size = 2
  ) +

  scale_x_continuous(
    breaks = seq(1955, 2025, by = 5)
  ) +

  labs(
    title = "Number of Billboard #1 Hits per Year",
    subtitle = "Distribution of songs across years",
    x = "Year",
    y = "Number of hits"
  ) +

  theme_minimal(base_size = 13) +

  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```
```{R}
# Popularity of collab songs
billboard_test %>%
  mutate(year = as.numeric(year)) %>%
  group_by(year) %>%
  summarise(
    collab_percent = mean(is_collab, na.rm = TRUE) * 100
  ) %>%
  ggplot(aes(x = year, y = collab_percent)) +
  geom_line(color = "#4E79A7", linewidth = 1.2) +
  geom_point(color = "#4E79A7", size = 2) +
  theme_minimal(base_size = 13) +

  labs(
    title = "Popularity of Collaboration Songs Over Time",
    subtitle = "Percentage of Billboard #1 songs that were collaborations",
    x = "Year",
    y = "% of collaboration songs"
  )
```
```{R}
ggplot(billboard_test, aes(x = song_title_length)) +
  geom_histogram(
    binwidth = 2,
    fill = "#4E79A7",
    color = "white",
    alpha = 0.9
  ) +
  labs(
    title = "Distribution of Song Title Lengths",
    subtitle = "Most Billboard #1 songs have relatively short titles",
    x = "Song title length (characters)",
    y = "Number of songs"
  ) +
  theme_minimal(base_size = 13)
```

```{R}
# Titles got slightly shorter over time
ggplot(billboard_test,
       aes(x = decade, y = song_title_length, fill = decade)) +
  geom_boxplot()
```

```{R}
# Top 10 artists with most hit songs
billboard_test %>%
  count(artist, sort = TRUE) %>%
  slice_head(n = 10) %>%
  ggplot(aes(x = reorder(artist, n), y = n)) +
  geom_col(fill="#4E79A7") +
  coord_flip() +
  labs(title="Top 10 aritsts with most hit songs")
```
```{R}
billboard_test %>%
  count(decade, season) %>%

  ggplot(aes(x = decade, y = season, fill = n)) +

  geom_tile(color = "white", linewidth = 1) +

  geom_text(
    aes(label = n),
    color = "white",
    size = 5
  ) +

  scale_fill_gradient(
    low = "#A8DADC",
    high = "#1D3557"
  ) +

  labs(
    title = "Billboard #1 Hits by Season and Decade",
    subtitle = "Darker colors indicate more songs",
    x = "Decade",
    y = "Season",
    fill = "Songs"
  ) +

  theme_minimal(base_size = 13) +

  theme(
    panel.grid = element_blank(),
    axis.text.x = element_text(face = "bold"),
    axis.text.y = element_text(face = "bold")
  )
```


## Interesting statistics

```{R}
(sum(billboard_test["artist_is_only_songwriter"]) / count(billboard_test["artist_is_only_songwriter"])) * 100
### This percent of Artist wrote the songs themselves
```



```{R}
(count(billboard_test["artist_is_a_songwriter"]) - sum(billboard_test["artist_is_a_songwriter"]))/count(billboard_test["artist_is_a_songwriter"]) *100

### This percent of artist haven't even contributed to the writing process
```

```{R}
sum(billboard_test$is_collab) / count(billboard_test) * 100
# percentage of songs that are collabs
```
















































